-- 5

----------------
-- ITALIANO 2 --
----------------
-- Gare
insert into gara (data, IDtorneo) values ('2016-01-15', 8);
insert into gara (data, IDtorneo) values ('2016-01-14', 8);
insert into gara (data, IDtorneo) values ('2016-01-13', 8);
insert into gara (data, IDtorneo) values ('2016-01-12', 8);
insert into gara (data, IDtorneo) values ('2016-01-11', 8);
insert into gara (data, IDtorneo) values ('2016-01-10', 8);
insert into gara (data, IDtorneo) values ('2016-01-09', 8);
insert into gara (data, IDtorneo) values ('2016-01-08', 8);
insert into gara (data, IDtorneo) values ('2016-01-07', 8);
insert into gara (data, IDtorneo) values ('2016-01-06', 8);
insert into gara (data, IDtorneo) values ('2016-01-05', 8);
insert into gara (data, IDtorneo) values ('2016-01-04', 8);
insert into gara (data, IDtorneo) values ('2016-01-03', 8);
insert into gara (data, IDtorneo) values ('2016-01-02', 8);
insert into gara (data, IDtorneo) values ('2016-01-01', 8);
insert into gara (data, IDtorneo) values ('2015-12-31', 8);
insert into gara (data, IDtorneo) values ('2015-12-30', 8);
insert into gara (data, IDtorneo) values ('2015-12-29', 8);
insert into gara (data, IDtorneo) values ('2015-12-28', 8);
insert into gara (data, IDtorneo) values ('2015-12-27', 8);
insert into gara (data, IDtorneo) values ('2015-12-26', 8);
insert into gara (data, IDtorneo) values ('2015-12-25', 8);
insert into gara (data, IDtorneo) values ('2015-12-24', 8);
insert into gara (data, IDtorneo) values ('2015-12-23', 8);
insert into gara (data, IDtorneo) values ('2015-12-22', 8);
insert into gara (data, IDtorneo) values ('2015-12-21', 8);
insert into gara (data, IDtorneo) values ('2015-12-20', 8);
insert into gara (data, IDtorneo) values ('2015-12-19', 8);
insert into gara (data, IDtorneo) values ('2015-12-18', 8);
insert into gara (data, IDtorneo) values ('2015-12-17', 8);
insert into gara (data, IDtorneo) values ('2015-12-16', 8);
insert into gara (data, IDtorneo) values ('2015-12-15', 8);
insert into gara (data, IDtorneo) values ('2015-12-14', 8);
insert into gara (data, IDtorneo) values ('2015-12-13', 8);
insert into gara (data, IDtorneo) values ('2015-12-12', 8);
insert into gara (data, IDtorneo) values ('2015-12-11', 8);
insert into gara (data, IDtorneo) values ('2015-12-10', 8);
insert into gara (data, IDtorneo) values ('2015-12-09', 8);
insert into gara (data, IDtorneo) values ('2015-12-08', 8);
insert into gara (data, IDtorneo) values ('2015-12-07', 8);
insert into gara (data, IDtorneo) values ('2015-12-06', 8);
insert into gara (data, IDtorneo) values ('2015-12-05', 8);
insert into gara (data, IDtorneo) values ('2015-12-04', 8);
insert into gara (data, IDtorneo) values ('2015-12-03', 8);
insert into gara (data, IDtorneo) values ('2015-12-02', 8);

-- partecipanti
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (9, '114', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (17, '114', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (9, '115', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (14, '115', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (9, '116', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (12, '116', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (9, '117', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (6, '117', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (9, '118', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (7, '118', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (9, '119', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (10, '119', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (9, '120', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (8, '120', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (14, '121', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (8, '121', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (14, '122', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (12, '122', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (14, '123', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (6, '123', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (14, '124', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (7, '124', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (10, '125', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (7, '125', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (10, '126', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (14, '126', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (10, '127', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (8, '127', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (10, '128', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (6, '128', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (10, '129', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (12, '129', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (6, '130', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (12, '130', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (6, '131', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (7, '131', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (6, '132', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (8, '132', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (15, '133', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (12, '133', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (15, '134', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (10, '134', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (15, '135', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (5, '135', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (15, '136', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (17, '136', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (15, '137', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (6, '137', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (15, '138', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (14, '138', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (15, '139', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (7, '139', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (15, '140', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (8, '140', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (15, '141', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (9, '141', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (7, '142', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (12, '142', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (17, '143', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (6, '143', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (17, '144', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (10, '144', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (17, '145', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (7, '145', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (17, '146', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (14, '146', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (17, '147', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (8, '147', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (17, '148', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (12, '148', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (5, '149', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (17, '149', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (5, '150', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (14, '150', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (5, '151', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (9, '151', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (5, '152', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (10, '152', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (5, '153', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (7, '153', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (5, '154', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (6, '154', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (5, '155', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (12, '155', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (5, '156', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (8, '156', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (8, '157', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (12, '157', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (8, '158', null, null);
insert into partecipa_a (IDutente, IDgara, punteggio, risultato) values (7, '158', null, null);

-- faccio finire il torneo
select set_fine(8);